/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author N
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jdpMenuPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiAbmAlumnos = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiAbmMaterias = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jmiAbmInscripciones = new javax.swing.JMenuItem();
        jmiAbmNotas = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsultaAlumnosPorMateria = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpMenuPrincipalLayout = new javax.swing.GroupLayout(jdpMenuPrincipal);
        jdpMenuPrincipal.setLayout(jdpMenuPrincipalLayout);
        jdpMenuPrincipalLayout.setHorizontalGroup(
            jdpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        jdpMenuPrincipalLayout.setVerticalGroup(
            jdpMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");

        jmiAbmAlumnos.setText("Formulario de Alumno");
        jmiAbmAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbmAlumnosActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiAbmAlumnos);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmiAbmMaterias.setText("Formulario de Materia");
        jmiAbmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbmMateriasActionPerformed(evt);
            }
        });
        jmMateria.add(jmiAbmMaterias);

        jMenuBar1.add(jmMateria);

        jmAdministracion.setText("Administración");

        jmiAbmInscripciones.setText("Manejo de Inscripciones");
        jmiAbmInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbmInscripcionesActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiAbmInscripciones);

        jmiAbmNotas.setText("Manipulacion de notas");
        jmiAbmNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAbmNotasActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiAbmNotas);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmiConsultaAlumnosPorMateria.setText("Alumnos por materia");
        jmiConsultaAlumnosPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaAlumnosPorMateriaActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaAlumnosPorMateria);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpMenuPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAbmAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbmAlumnosActionPerformed
        // TODO add your handling code here:
        jdpMenuPrincipal.removeAll();
        jdpMenuPrincipal.repaint();
        frmAlumnos formulario = new frmAlumnos();
        formulario.setVisible(true);
        jdpMenuPrincipal.add(formulario);
        jdpMenuPrincipal.moveToFront(formulario);
    }//GEN-LAST:event_jmiAbmAlumnosActionPerformed

    private void jmiAbmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbmMateriasActionPerformed
        // TODO add your handling code here:
        jdpMenuPrincipal.removeAll();
        jdpMenuPrincipal.repaint();
        frmMaterias formulario = new frmMaterias();
        formulario.setVisible(true);
        jdpMenuPrincipal.add(formulario);
        jdpMenuPrincipal.moveToFront(formulario);
    }//GEN-LAST:event_jmiAbmMateriasActionPerformed

    private void jmiAbmInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbmInscripcionesActionPerformed
        // TODO add your handling code here:
        jdpMenuPrincipal.removeAll();
        jdpMenuPrincipal.repaint();
        frmInscripciones formulario = new frmInscripciones();
        formulario.setVisible(true);
        jdpMenuPrincipal.add(formulario);
        jdpMenuPrincipal.moveToFront(formulario);
    }//GEN-LAST:event_jmiAbmInscripcionesActionPerformed

    private void jmiAbmNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAbmNotasActionPerformed
        // TODO add your handling code here:
        jdpMenuPrincipal.removeAll();
        jdpMenuPrincipal.repaint();
        frmNotas formulario = new frmNotas();
        formulario.setVisible(true);
        jdpMenuPrincipal.add(formulario);
        jdpMenuPrincipal.moveToFront(formulario);
    }//GEN-LAST:event_jmiAbmNotasActionPerformed

    private void jmiConsultaAlumnosPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaAlumnosPorMateriaActionPerformed
        // TODO add your handling code here:
        jdpMenuPrincipal.removeAll();
        jdpMenuPrincipal.repaint();
        frmAlumnosPorMateria formulario = new frmAlumnosPorMateria();
        formulario.setVisible(true);
        jdpMenuPrincipal.add(formulario);
        jdpMenuPrincipal.moveToFront(formulario);
    }//GEN-LAST:event_jmiConsultaAlumnosPorMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JDesktopPane jdpMenuPrincipal;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenuItem jmiAbmAlumnos;
    private javax.swing.JMenuItem jmiAbmInscripciones;
    private javax.swing.JMenuItem jmiAbmMaterias;
    private javax.swing.JMenuItem jmiAbmNotas;
    private javax.swing.JMenuItem jmiConsultaAlumnosPorMateria;
    // End of variables declaration//GEN-END:variables
}
